spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 40MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

auth:
  providers:
    kakao:
      authorize_uri: https://kauth.kakao.com/oauth/authorize
      client_id: ${KAKAO_CLIENT_ID}
      redirect_uri: ${KAKAO_REDIRECT_URI}
      grant_type: ${KAKAO_GRANT_TYPE}
      token_uri: ${KAKAO_TOKEN_URI}
      user_info_uri: ${KAKAO_USER_INFO_URI}
  jwt:
    private-key: ${JWT_PRIVATE_KEY}
    public-key: ${JWT_PUBLIC_KEY}
