spring:
  datasource:
    url: ${DB_URL}
    username: ${RDS_USER_NAME}
    password: ${RDS_USER_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
weeth:
  jwt:
    key: ${JWT_KEY}
    access:
      expiration: 3600000 # 1시간
      header: Authorization
    refresh:
      expiration: 1209600000 # 2주
      header: Authorization-refresh