spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weeth
    username: admin
    password: Weeth1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB
      resolve-lazily: true

weeth:
  jwt:
    key: f825f47437e5088c37e9e1fcd93fbc61dbb06d54b34471e47e9475e6f607d35f
    access:
      expiration: ${ACCESS_EXP}
      header: ${ACCESS_HEAD}
    refresh:
      expiration: ${REFRESH_EXP}
      header: ${REFRESH_HEAD}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false