spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 40MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha